
version: 2

models:
  - name: fact_tickets
    description: "tickets Information"
    columns: 
      - name: book_date
      - name: dbt_time
      - name: total_amount
      - name: book_ref
      - name: ticket_no
      - name: passenger_id
      - name: passenger_name
      - name: phone_number
        description: "json extraction"
      - name: email_address
        description: "json extraction"
        tests:
          - unique
          - not_null



models:
  - name: fact_boarding
    description: "boarding and flight tickets Information"
    columns: 
      - name: fare_conditions
      - name: amount
      - name: ticket_no
      - name: flight_id
      - name: boarding_no
      - name: seat_no
        tests:
          - unique
          - not_null




models:
  - name: fact_flights
    description: "flights Information"
    columns: 
      - name: fare_conditions
      - name: amount
      - name: ticket_no
      - name: flight_id
      - name: boarding_no
      - name: seat_no
        tests:
          - unique
          - not_null



sources:
  - name: flight_demo_fact
    database: flight_demo
    schema: stg
    tables:
      - name: bookings
      - name: tickets
      - name: boarding_passes
      - name: ticket_flights
      - name: flights

 